// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function GetAgentList() {
  return window['go']['main']['App']['GetAgentList']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
