// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {agent} from '../models';

export function Execute(arg1:main.ExecuteRequest):Promise<main.ExecuteResponse>;

export function GetAgentList():Promise<Array<main.AgentInfo>>;

export function GetAgents():Promise<Array<Record<string, any>>>;

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetSettings():Promise<main.UserSettings>;

export function GetUsageStats():Promise<Array<agent.AgentUsageItem>>;

export function GetVersion():Promise<Record<string, string>>;

export function SaveSettings(arg1:main.UserSettings):Promise<boolean>;
